name = "gemini-proxy"
compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]
main = "./worker.js"

# Automatically place your workloads in an optimal location to minimize latency.
# If you are running back-end logic in a Pages Function, running it closer to your back-end infrastructure
# rather than the end user may result in better performance.
# Docs: https://developers.cloudflare.com/pages/functions/smart-placement/#smart-placement
[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "geo-us-east"
database_id = "fd1fe1b7-b556-4692-9f00-13f175e30d51"
