name = "gemini-proxy"
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat"]
main = "./worker.js"

[[migrations]]
tag = "v1"
new_classes = [ "GeminiProxy" ]

# Automatically place your workloads in an optimal location to minimize latency.
# If you are running back-end logic in a Pages Function, running it closer to your back-end infrastructure
# rather than the end user may result in better performance.
# Docs: https://developers.cloudflare.com/pages/functions/smart-placement/#smart-placement
[placement]
mode = "smart"

[[durable_objects.bindings]]
name = "MY_DURABLE_OBJECT"
class_name = "GeminiProxy"
